### ISSUE TITLE
mfcuk error code 03

### ISSUE THREAD

**Issue by aleks921** [nfc-tools/mfcuk#34]
I try hack mifare classic card with MFCUK on kali linux.
But I get an error every 10-20 authorizations (auth)

My log from mfcuk after about one hour.

Let me entertain you!
uid: 7412d10c
type: 08
key: 000000000000
block: 03
diff Nt: 45
## auths: 9623

mfcuk: ERROR: mfcuk_key_recovery_block() (error code=0x03)

Can you say me that about error code = 03 ? Is it fixed card or not ?
Brute force is necessary to stop?

**Comment by ArchangeGabriel** [comment]
See #39.
