### ISSUE TITLE
How compile mfcuk

### ISSUE THREAD

**Issue by aleks921** [nfc-tools/mfcuk#35]
How compile mfcuk on ubuntu linux ? 
I can't compile this tools.

**Comment by slango20** [comment]
the readme is off for compiling, the series of commands you need to run is

```
libtoolize
aclocal
autoconf
autoheader
automake --add-missing
automake
./configure
make
```

**Comment by alvarotorijano** [comment]
I'm doing the same, I've already instaled libnfc-bin_1.7.0-3_i386.deb but ./configure stil says 
error: libnfc >= 1.7.0 is mandatory.
Please help

**Comment by smortex** [comment]
Instructions are now up-to-date. Closing.

**Comment by anon-sportycto** [comment]
> I'm doing the same, I've already instaled libnfc-bin_1.7.0-3_i386.deb but ./configure stil says error: libnfc >= 1.7.0 is mandatory. Please help

sudo apt-get install libnfc-dev
