### ISSUE TITLE
Mfcuk svn repository

### ISSUE THREAD

**Issue by amoeles** [nfc-tools/mfcuk#38]
Is there any way to retrieve old revisions of mfcuk after googlecode down?

example: http://mfcuk.googlecode.com/svn/trunk/mfcuk-r65

**Comment by unixpapers** [comment]
It seems like the code has been moved to Github. The following link leads to r65:

https://github.com/nfc-tools/mfcuk/commit/1b6d022668080aa761a4e2bea8c24c1f7aa537db

To checkout that particular revision with git you can use:
git clone https://github.com/nfc-tools/mfcuk mfcuk-r65
cd mfcuk-r65
git reset --hard 1b6d022668080aa761a4e2bea8c24c1f7aa537db

But I have problem mfcuk: ERROR: mfcuk_key_recovery_block() (error code=0x03) with all version mfcuk and libnfc

**Comment by amoeles** [comment]
Thanks, if you want i try help you, i'm "amoeles" in telegram

**Comment by amoeles** [comment]
git clone https://github.com/nfc-tools/mfcuk mfcuk-r65 

The command don't work, always install the lastest version.

**Comment by amoeles** [comment]
This is the way (font: https://zozs.se/2014/08/18/acr122u-mfcuk-mfoc-cracking-mifare-classic-on-arch-linux/) :
The following link leads to r65:
https://github.com/nfc-tools/mfcuk/commit/1b6d022668080aa761a4e2bea8c24c1f7aa537db
To checkout that particular revision with git you can use:
git clone https://github.com/nfc-tools/mfcuk mfcuk-r65
cd mfcuk-r65
git reset --hard 1b6d022668080aa761a4e2bea8c24c1f7aa537db

**Comment by unixpapers** [comment]
Already checked out the same ERROR: mfcuk_key_recovery_block () (error code = 0x03)

You have turned on this article?

**Comment by amoeles** [comment]
What is your hardware? Do you obtain the same error with another tag?

**Comment by unixpapers** [comment]
Adafruit PN532 RFID/NFC Breakout, yes I' try use blank tag with standart key ffffffffffff, mfoc get keys, but mfcuk not crack and display list ERROR: mfcuk_key_recovery_block () (error code = 0x03)

**Comment by tutan7** [comment]
I'm trying to avoid the  error code = 0x03 by installing MFCUK R65 but unable to compile.

Im puting the code:
cd mfcuk-r65
$ autoreconf -is
$ LIBNFC_CFLAGS=-I/home/kali/builds/nfc/prefix/include LIBNFC_LIBS="-L/home/kali/builds/nfc/prefix/lib -lnfc" ./configure --prefix=/home/kali/builds/nfc/prefix
$ make
$ make install
$ cd ..

Then im receiving the errors:
Making install in src
make[1]: Entering directory '/home/kali/mftest/mfcuk-r65/src'
  CC       mifare.o
In file included from mifare.c:35:
mifare.h:79:34: error: unknown type name ‘nfc_device’; did you mean ‘nfc_device_t’?
   79 | bool    nfc_initiator_mifare_cmd(nfc_device *pnd, const mifare_cmd mc, const uint8_t ui8Block, mifare_param *pmp);
      |                                  ^~~~~~~~~~
      |                                  nfc_device_t
mifare.c:55:26: error: unknown type name ‘nfc_device’; did you mean ‘nfc_device_t’?
   55 | nfc_initiator_mifare_cmd(nfc_device *pnd, const mifare_cmd mc, const uint8_t ui8Block, mifare_param *pmp)
      |                          ^~~~~~~~~~
      |                          nfc_device_t
make[1]: *** [Makefile:389: mifare.o] Error 1
make[1]: Leaving directory '/home/kali/mftest/mfcuk-r65/src'
make: *** [Makefile:369: install-recursive] Error 1


Please help!
PS. Im using Kali USB Live + PN532 (+UART).
