### ISSUE TITLE
how to find out whether my card is java card according to sak 28

### ISSUE THREAD

**Issue by lweo** [nfc-tools/mfcuk#40]
have run command nfc-list:

displaying:

nfc-list uses libnfc 1.7.1
NFC device: pn532_uart:/dev/ttyUSB0 opened
1 ISO14443A passive target(s) found:
ISO/IEC 14443A (106 kbps) target:
ATQA (SENS_RES): 00 04

UID (NFCID1): d3 a7 a3 12

SAK (SEL_RES): 28

ATS: 78 80 a0 02 20 90 00 00 00 00 00 d3 a7 a3 12

I have looked up information from AN10833, according the document it seems like be MIFARE
Classic 1KB+ MIFARE plus or MIFARE Classic 1KB+ MIFARE DESFire or…
or even maybe a java card JCOP41 v2.3.1?

I cant determine which type so I can't do other things. when I use mfoc, it tells me " Cannot determine card type from SAK"

any idea?

**Comment by smortex** [comment]
Please use the [NFC-Tools Forums](http://forums.nfc-tools.org/) for questions/help, where a wider community will be able to help you. We reserve the *issues* tracker for **issues** only.
