### ISSUE TITLE
Segmentation fault when data files are not found

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/mfcuk#5]
```
What steps will reproduce the problem?
1. ./configure
2. make
3. src/mfcuk_keyrecovery_darkside -C


```

Original issue reported on code.google.com by `romu...@libnfc.org` on 1 Apr 2011 at 9:26

**Comment by aev1tas** [comment]
I've installed mfcuk with homebrew and I still get this error, because I don't have a data folder or mfcuk_keyrecovery_darkside file. I am running Mac OS X 10.10.3 with the newest homebrew.

How can I fix this?

**Comment by logless** [comment]
Enter the directory of mfcuk within Homebrew (usually /Cellar/mfcuk/0.3.8/ then enter the bin directory and place the /data/ directory inside (get the data directory from `https://github.com/S0c5/mfcuk_fix/tree/master/data`  (you actually only need the tmpls_fingerprints directory to fix the errors). After you place it in, start mfcuk from within the /bin/ directory. The errors should be gone.

**Comment by TheodoreDean** [comment]
> Enter the directory of mfcuk within Homebrew (usually /Cellar/mfcuk/0.3.8/ then enter the bin directory and place the /data/ directory inside (get the data directory from `https://github.com/S0c5/mfcuk_fix/tree/master/data` (you actually only need the tmpls_fingerprints directory to fix the errors). After you place it in, start mfcuk from within the /bin/ directory. The errors should be gone.

If install by using Homebrew, after put the data directory at /Cellar/mfcuk/x.x.x, just start mfcuk, the error is disppear.
