### ISSUE TITLE
./configure: line 3739: syntax error near unexpected token `LIBNFC,'

### ISSUE THREAD

**Issue by Elkhazrajy** [nfc-tools/mfcuk#70]
I am trying to compile this mfcuk version
https://github.com/DrSchottky/mfcuk

I get this error on kali when I try to compile mfcuk
![image](https://user-images.githubusercontent.com/24656918/54087095-8420ec80-4347-11e9-9d01-4e5b605f47c8.png)

**Comment by neomilium** [comment]
> I am trying to compile this mfcuk version
> https://github.com/DrSchottky/mfcuk
… So report it at right place.
