### ISSUE TITLE
mfcuk: ERROR: connecting to NFC reader

### ISSUE THREAD

**Issue by andrearizzello** [nfc-tools/mfcuk#74]
Hello, i'm using a RFIO-RC522 [this one](https://www.makerfabs.com/index.php?route=product/product&product_id=66) as reader/writer but i get the error `mfcuk: ERROR: connecting to NFC reader`
The wiring process is ok (tested with some python scripts) but the program doesn't detect the reader
What could i do? do i miss some other dependences?

I also get some other warnings just before the message
`WARN: cannot open template file './data/tmpls_fingerprints/mfcuk_tmpl_skgt.mfd'
WARN: cannot open template file './data/tmpls_fingerprints/mfcuk_tmpl_ratb.mfd'
WARN: cannot open template file './data/tmpls_fingerprints/mfcuk_tmpl_oyster.mfd'`

**Comment by 0x5ECF4ULT** [comment]
Looks like the file permissions are messed up. Try with `sudo`

**Comment by andrearizzello** [comment]
As i didn't find a solution on time, i sent back the reader
So i'm not able to test this anymore 😕
